general:
  debug: False # 调试模式,若设为true,则不会真正的移动文件,但会更新信息.

  media_dir: 'H:\Video' # 源文件夹
  target_dir: 'H:\Video\Porn' # 目标文件夹
  ignore_file: 'gavdener.ignore' # 忽略标记, 存在该文件则不处理同级目录下的所有影片
  info_file: 'gavdener-info.yml' # 影片信息

spider:
  resource_sites: # 资源站顺序(目前只支持javbus,墙内访问需挂梯)
    - 'javbus'
  proxy: # 代理配置, 如无需代理请删除
    http: 'http://127.0.0.1:10809'
    https: 'http://127.0.0.1:10809'
  timeout: 10
  retry: 3

scrapper:
  target_exts: # 文件类型,仅列出的文件类型会被处理.
    - '.mp4'
    - '.avi'
    - '.rmvb'
    - '.wmv'
    - '.mov'
    - '.mkv'
    - '.flv'
    - '.ts'
    - '.webm'
  multi_actors: true # 影片具有多个演员时,该项为true,则会在其余演员文件夹下创建目录及链接;否则仅取首位演员.